#pragma once
#include <array>
#include <string>
#include "FAIDefine.h"

/////////// MAX_DEF /////////////////// CMI 3000
#define MAX_DEF			(999999999)

//Window cordinations...
#ifndef DEFINE_HEADER
#define DEFINE_HEADER

#define SCREEN_WIDTH	1920
#define SCREEN_HEIGHT	1080

#define LR_MARGIN		2
#define STATUS_HEIGHT	33

#define RECTWIDTH(lpRect)	((lpRect)->right - (lpRect)->left)
#define RECTHEIGHT(lpRect)	((lpRect)->bottom - (lpRect)->top)

// For Inspection ...
#define VIEW1_DLG1_LEFT		(LR_MARGIN)								// 1.Inspect View1
#define VIEW1_DLG2_LEFT		(LR_MARGIN + 700)						// 2.Inspect View2
#define VIEW1_DLG3_LEFT		(LR_MARGIN + 900)						// 3.Inspect Summary
#define VIEW1_DLG4_LEFT		(LR_MARGIN + 900)						// 4.FM1
#define VIEW1_DLG5_LEFT		(VIEW1_DLG3_LEFT + SCREEN_WIDTH) / 2	// 5.FM2
#define VIEW1_DLG6_LEFT		(LR_MARGIN + 900)						// 6.Pad Image
#define VIEW1_DLG7_LEFT		(LR_MARGIN)								// 7.Inspect Result

#define VIEW1_DLG1_TOP		(160)
#define VIEW1_DLG2_TOP		(160)
#define VIEW1_DLG3_TOP		(110)
#define VIEW1_DLG4_TOP		(310)
#define VIEW1_DLG5_TOP		(310)
#define VIEW1_DLG6_TOP		(595)
#define VIEW1_DLG7_TOP		(700)

#define VIEW1_DLG1_WIDTH	(VIEW1_DLG2_LEFT - VIEW1_DLG1_LEFT-10)
#define VIEW1_DLG2_WIDTH	(VIEW1_DLG1_WIDTH)
#define VIEW1_DLG3_WIDTH	(SCREEN_WIDTH - VIEW1_DLG3_LEFT)
#define VIEW1_DLG4_WIDTH	(VIEW1_DLG5_LEFT - VIEW1_DLG4_LEFT)
#define VIEW1_DLG5_WIDTH	(VIEW1_DLG4_WIDTH)
#define VIEW1_DLG6_WIDTH	(VIEW1_DLG3_WIDTH)
#define VIEW1_DLG7_WIDTH	(VIEW1_DLG3_LEFT - VIEW1_DLG7_LEFT)

#define VIEW1_DLG1_HEIGHT	(VIEW1_DLG7_TOP - VIEW1_DLG1_TOP)
#define VIEW1_DLG2_HEIGHT	(VIEW1_DLG1_HEIGHT)
#define VIEW1_DLG3_HEIGHT	(VIEW1_DLG4_TOP - VIEW1_DLG3_TOP)
#define VIEW1_DLG4_HEIGHT	(VIEW1_DLG6_TOP - VIEW1_DLG4_TOP)
#define VIEW1_DLG5_HEIGHT	(VIEW1_DLG4_HEIGHT)
#define VIEW1_DLG6_HEIGHT	(SCREEN_HEIGHT - VIEW1_DLG6_TOP - STATUS_HEIGHT)
#define VIEW1_DLG7_HEIGHT	(SCREEN_HEIGHT - VIEW1_DLG7_TOP - STATUS_HEIGHT)

#define VIEW_TOOLBAR_HEIGHT	40

// For Teaching ...
#define VIEW2_DLG1_LEFT		(LR_MARGIN)			// 1.Image Display
#define VIEW2_DLG2_LEFT		(LR_MARGIN + 880)	// 2.PCB/PAD Sheet (TeachingService)
#define VIEW2_DLG3_LEFT		(LR_MARGIN)			// 3.Inspect Condition

#define VIEW2_DLG1_TOP		(110)
#define VIEW2_DLG2_TOP		(110)
#define VIEW2_DLG3_TOP		(800)

#define VIEW2_DLG1_WIDTH	(VIEW2_DLG2_LEFT - VIEW2_DLG1_LEFT)
#define VIEW2_DLG2_WIDTH	(SCREEN_WIDTH - VIEW2_DLG2_LEFT)
#define VIEW2_DLG3_WIDTH	(VIEW2_DLG1_WIDTH)

#define VIEW2_DLG1_HEIGHT	(VIEW2_DLG3_TOP - VIEW2_DLG1_TOP)
#define VIEW2_DLG2_HEIGHT	(SCREEN_HEIGHT - VIEW2_DLG1_TOP - STATUS_HEIGHT)
#define VIEW2_DLG3_HEIGHT	(SCREEN_HEIGHT - VIEW2_DLG3_TOP - STATUS_HEIGHT)

// ex)
// SetPosition(VIEW1_DLG1_LEFT, VIEW1_DLG1_TOP, VIEW1_DLG1_WIDTH, VIEW1_DLG1_HEIGHT);

#define WM_DISPLAY_TRAY 2184


//////////////////////////////////////////////////////////////////////////
/// PC Setting
//////////////////////////////////////////////////////////////////////////
// PC Index
#define PC_NUMBER_MAX 5
#define PC_NUMBER_1 0
#define PC_NUMBER_2 1
#define PC_NUMBER_3 2
#define PC_NUMBER_4 3
#define PC_NUMBER_5 4

// Vision Index
#define VISION_NUMBER_MAX	4
#define VISION_NUMBER_1		0
#define VISION_NUMBER_2		1
#define VISION_NUMBER_3		2
#define VISION_NUMBER_4		3
#define VISION_NUMBER_4_2	4
#define VISION_NUMBER_4_3	5

#define TOTAL_SUB_CAM		2
#define SUB_CAM_1			0
#define SUB_CAM_2			1

// Align Cam Index
#define ALIGN_CAM_NUMBER_MAX	3
#define ALIGN_CAM_BOTTOM_1		0
#define ALIGN_CAM_BOTTOM_2		1
#define ALIGN_CAM_TOP			2

// Stage Index
#define STAGE_NUMBER_MAX	2
#define STAGE_NUMBER_1		0
#define STAGE_NUMBER_2		1

#define INVALID_LASER_DATA		-1000000000
#define LASER_SCAN_LENGTH			1800
#define LASER_LINE_MULTIPLIER		1
#define IMAGE_WIDTH_LASER			3200
#define IMAGE_HEIGHT_LASER			LASER_SCAN_LENGTH*LASER_LINE_MULTIPLIER

#define DUMMY_IMAGE_SIZE	512

// LM Max Page Number / One Vision

#ifdef POC_TEST
	#define LIGHTCTRL_TEACHING_GRAB_ADDR_INDEX	0		// 임시
#else
	#define LIGHTCTRL_TEACHING_GRAB_ADDR_INDEX	17
#endif

#define LIGHTCTRL_GRAB_ADDR_SEQ_COUNT		17		// 7 -> 13 -> 17
#define LIGHTCTRL_GRAB_ADDR_PAGE_COUNT		16		// 분리
#define LIGHTCTRL_PAGE_COUNT				32		// 16 -> 32
#define LIGHTCTRL_PAGE_COUNT_4CH			6
#define LIGHTCTRL_PAGE_COUNT_6CH			10
#define LIGHTCTRL_PAGE_COUNT_8CH			10
#define LIGHTCTRL_PAGE_COUNT_2CH			6
#define LIGHTCTRL_PAGE_COUNT_BTM_ALIGN		3
#define LIGHTCTRL_PAGE_COUNT_TOP_ALIGN		2

////////////// Light Control ////////////////////
//#define LIGHT_BRIGHT_MAX 999
//#define LIGHT_CH_CNT	10
#define LIGHT_BRIGHT_MAX 1023
#define LIGHT_CH_CNT	32			// 24 -> 32

#define LIGHT_PWM_MAX	1023
#define PWM_PAGE_COUNT	1
#define PWM_CH_CNT		4

#define GRAB_SEQ_IO_BIT		7

// Laser
#define DEVICEID						0
#define MAX_LASER_HEAD_NUM				2
#define MAX_LASER_SCAN_NUMBER			5

#ifdef INLINE_MODE
#ifdef SINGLE_LENS
#define INSPECTION_BUFFER_COUNT_MAX		60
#else
#define INSPECTION_BUFFER_COUNT_MAX		20
#endif
#else
	#ifdef ONE_THREAD_INSPECTION
		#define INSPECTION_BUFFER_COUNT_MAX	1
	#else
		#define INSPECTION_BUFFER_COUNT_MAX	MAX_MODULE_TRAY
	#endif
#endif

#ifdef SINGLE_LENS
#define GRAB_CIRCULAR_MAX			6
#else
#define GRAB_CIRCULAR_MAX			3
#endif

#define LC_OPERATION_RESET	0
#define LC_OPERATION_ADD	1
#define LC_OPERATION_SUB	2

#define GRAB_X_MAX		1152	// 
#define GRAB_Y_MAX		1152	// 

//////////////////////////////////////////////////////////////////////////

#define UM_SHEET_CLOSED WM_USER+300

#define UM_SCANDONE		WM_USER+200

#define UM_2DFRAME_READY WM_USER+102

#define UM_FMARK_DISPLAY		WM_USER+511

#define UMSG_SAVE_IMAGE_DONE	WM_USER + 512
#define UM_RS_GOTO_DEFECT		WM_USER + 513

#define UM_TS_ROI_SELECTED		WM_USER + 514
#define UM_TS_ROI_INSPECTION_TAB_SAVE	WM_USER + 515

#define UM_LIST_SELECT		WM_USER + 601
#define UM_LIST_DBCLICK		WM_USER + 602
#define UM_LIST_DELETE		WM_USER + 603
#define UM_LIGHT_LIST_APPLY	WM_USER + 604

//////////////////////////////////////////////////////////////////////////
#define WM_START_REVIEW		5000
#define WM_CAPTURE_REVIEW	5001
#define WM_END_REVIEW		5002
#define WM_LIGHT_REVIEW		5003
#define WM_GET_DEFECT_NAME 5004
#define WM_SAVEIMAGE_DONE  5005
#define WM_DESTROY_DONE 5006

#define TS_COLOR_PAD					RGB(255,255,150)
#define TS_COLOR_BG						RGB( 38,132, 68)
#define TS_COLOR_FIDUCIAL				RGB(  0,  0,255)
#define TS_COLOR_MOLD					RGB(238, 82,238)
#define TS_COLOR_BLACK_BG				RGB(0, 0, 0)

#define TS_COLOR_SELECTED_PAD			RGB(255,  0,128)
#define TS_COLOR_REALPAD				RGB(128,255,255)
#define TS_COLOR_MANUALPAD				RGB(  0,255,  0)

#define TS_COLOR_INSPECTIING_FRAME		RGB( 52,184, 95)
#define TS_COLOR_PADINFO_TEXT			RGB(  0,  0,  0)
#define TS_COLOR_PADINFO_BG				RGB(255,255,255)

///////////////  Inspection View Gerber Color Definition  (2006/02/12)
#define TS_COLOR_INSPECTING_PAD			RGB(128,255,255)
#define TS_COLOR_RESULT_GOOD			RGB(  0,255,  0)
#define TS_COLOR_RESULT_ERROR			RGB(255,  0,  0)
#define TS_COLOR_RESULT_WARNING			RGB(255,128,  0)
#define TS_COLOR_RESULT_INSPECT_ERROR	RGB(  0,  0,  0)
#define TS_COLOR_RESULT_NO_PUNCH_ERROR	RGB(255,  0,  0)
#define TS_COLOR_EXTRA_BG				RGB( 75, 75, 75)
#define TS_INSPECT_PCB_MARGIN			50
/////////////////

///////////////  Mode Switch
#define MODE_INSPECT_VIEW_ADMIN			1
#define MODE_INSPECT_VIEW_OPERATOR		2
#define MODE_ADMIN_TEACH_VIEW			3

///////////////  Defect Type
#define DEFECT_TYPE_FIRST	DEFECT_TYPE_BARCODE					// DEFECT_TYPE_BARREL -> DEFECT_TYPE_MODULE -> DEFECT_TYEE_BARCODE
#define DEFECT_TYPE_LAST	DEFECT_TYPE_CONNECTOR_STIFFENER		// DEFECT_TYPE_STIFFENER_SIDE -> DEFECT_TYPE_CONNECTOR_STIFFENER

#define DEFECT_TYPE_PROCESSING_ERROR		-2
#define DEFECT_TYPE_GOOD					-1
#define DEFECT_TYPE_BARCODE					0					// 1 -> 0
#define DEFECT_TYPE_BARREL					1					// 0 -> 1
#define DEFECT_TYPE_LENS					2					// New
#define DEFECT_TYPE_MODULE					3					// 3 ->
#define DEFECT_TYPE_VCM_TOP					4					// 7 -> 4
#define DEFECT_TYPE_STIFFENER_BOTTOM		5					// 4 -> 5
#define DEFECT_TYPE_FPCB1					6					// 2 -> 6
#define DEFECT_TYPE_FPCB2					7					// New
#define DEFECT_TYPE_FPCB3					8					// New
#define DEFECT_TYPE_VCM_SIDE1				9					// 8 -> 9
#define DEFECT_TYPE_VCM_SIDE2				10					// New
#define DEFECT_TYPE_VCM_SIDE3				11					// New
#define DEFECT_TYPE_VCM_SIDE4				12					// New
#define DEFECT_TYPE_STIFFENER_SIDE1			13					// 9 -> 13
#define DEFECT_TYPE_STIFFENER_SIDE2			14					// New
#define DEFECT_TYPE_STIFFENER_SIDE3			15					// New
#define DEFECT_TYPE_STIFFENER_SIDE4			16					// New
#define DEFECT_TYPE_BARREL_SIDE1			17					// New
#define DEFECT_TYPE_BARREL_SIDE2			18					// New
#define DEFECT_TYPE_BARREL_SIDE3			19					// New
#define DEFECT_TYPE_BARREL_SIDE4			20					// New
#define DEFECT_TYPE_CONNECTOR				21					// 5 -> 21
#define DEFECT_TYPE_CONNECTOR_STIFFENER		22					// 6 -> 22

#define DEFECT_TYPE_LIGHT_ERROR				31					// 21 -> 31
#define DEFECT_TYPE_GRAB_FAIL				32					// 22 -> 32
#define DEFECT_TYPE_ALIGN_ERROR				33					// 23 -> 33
#define DEFECT_TYPE_BARCODE_NOT_SAME		34					// 24 -> 34
#define DEFECT_TYPE_BARCODE_MIX				35					// 25 -> 35

////////////////////////////////////////////////////////////////////
/// New GUI (2016. 05. 29)

#define MAX_IMAGE_TAB		45			// 20 -> 45			
#define MAX_INSPECTION_TAB	7
#define MAX_RESULT_IMAGE	18

#ifdef INLINE_MODE
#if defined(SINGLE_LENS) || defined(ASSY_LENS)
	#define MAX_GRAB_BUFFER			MAX_IMAGE_TAB
#else
	#define MAX_GRAB_BUFFER			MAX_IMAGE_TAB + 30 + 6
#endif
	#define GRAB_BUFFER_VISION1		MAX_GRAB_BUFFER
	#define GRAB_BUFFER_VISION2		MAX_GRAB_BUFFER
	#define GRAB_BUFFER_VISION3		MAX_GRAB_BUFFER
	#define GRAB_BUFFER_VISION4		MAX_GRAB_BUFFER
#else
	#define MAX_GRAB_BUFFER			MAX_IMAGE_TAB
	#define GRAB_BUFFER_VISION1		MAX_IMAGE_TAB
	#define GRAB_BUFFER_VISION2		MAX_IMAGE_TAB
	#define GRAB_BUFFER_VISION3		MAX_IMAGE_TAB
	#define GRAB_BUFFER_VISION4		MAX_IMAGE_TAB
#endif

#define ALIGN_CAM_GRAB_NUMBER		1
#define MAX_MODULE_ALIGN_CAM_IMAGE	20
#define ALIGN_MODULE_X				4
#define ALIGN_MODULE_Y				5

//////////////////////////////////////////////////////////////////////////
/// Handler Status
#define HS_NOT_READY	0
#define HS_READY		1
#define HS_RUN			2
#define HS_RESET		3
#define HS_PAUSE		4
#define HS_CYCLE_STOP	5
#define HS_STOP			6

// 조명 컨트롤러 통신
#define LIGHT_CONTROLLER_NUMBER_MAX		4
#define LIGHT_CONTROLLER_NUMBER_1		0
#define LIGHT_CONTROLLER_NUMBER_2		1
#define LIGHT_CONTROLLER_NUMBER_3		2
#define LIGHT_CONTROLLER_NUMBER_4		3

#define EMPTY_TRAY_MODULE			-1

#define AF_MAX_DEVIATION_MM		1.0


static int g_iVisionMaxGrabBuffer[] =
{
	GRAB_BUFFER_VISION1,
	GRAB_BUFFER_VISION2,
	GRAB_BUFFER_VISION3,
	GRAB_BUFFER_VISION4
};

#define NO_MAX_INSPECT_THREAD						10

#define TEACHING_THREAD_INDEX						0
#define TEACHING_INSPECT_BUFFER_INDEX				0
#define TEACHING_MZ_NO								1
#define TEACHING_TRAY_NO							1
#define TEACHING_MODULE_NO							1
#define TEACHING_MODULE_NO_UNDEFINED				-1

#ifdef INLINE_MODE
	#ifdef POC_TEST
		#define MAX_MAGAZINE_NO			1
		#define MAX_TRAY_LOT			1
		#define MAX_MODULE_TRAY			40
	#else
		// TODO : Split by Model, dont use conditional compilation
		//		: dangling with FAI definition
		#define MAX_MAGAZINE_NO			3
		#ifdef UAVI_AKC
			#define MAX_TRAY_LOT			50
			#define MAX_MODULE_TRAY			12
		#endif
		#ifdef UAVI_CHS_KS
			#define MAX_TRAY_LOT			50
			#define MAX_MODULE_TRAY			12
		#endif
		#ifdef UAVI_CHS_WZ
			#define MAX_TRAY_LOT			25
			#define MAX_MODULE_TRAY			36
		#endif
		#ifdef UAVI_BOI
			#define MAX_TRAY_LOT			25
			#define MAX_MODULE_TRAY			20
		#endif
		#ifdef UAVI_ACT
			#define MAX_TRAY_LOT			1
			#define MAX_MODULE_TRAY			40
		#endif
		#ifdef UAVI_ATW
			#define MAX_TRAY_LOT			50
			#define MAX_MODULE_TRAY			15
		#endif
		#ifdef UAVI_CHS_TV
			#define MAX_TRAY_LOT			50
			#define MAX_MODULE_TRAY			12
		#endif
		#ifdef UAVI_BOS
			#define MAX_TRAY_LOT			25
			#define MAX_MODULE_TRAY			40
		#endif
		#ifdef UAVI_RENO
			#define MAX_TRAY_LOT			25
			#define MAX_MODULE_TRAY			25
		#endif
		#ifdef UAVI_KRIOS
			#define MAX_TRAY_LOT			25
			#define MAX_MODULE_TRAY			30
		#endif
		#ifdef SINGLE_LENS
			#define MAX_TRAY_LOT			10
			#define MAX_MODULE_TRAY			144
		#endif
		#ifdef ASSY_LENS
			#define MAX_TRAY_LOT			10
			#define MAX_MODULE_TRAY			40
		#endif
	#endif
#else
	#define MAX_MAGAZINE_NO			TEACHING_MZ_NO
	#define MAX_TRAY_LOT			50
	#define MAX_MODULE_TRAY			40
#endif

#ifdef INLINE_MODE
	#ifdef POC_TEST
		#define MODEL_DATA_MAX			1
	#else
		#define MODEL_DATA_MAX			2
	#endif
#else
	#define MODEL_DATA_MAX			1
#endif

#define MODEL_DATA_1			0
#define MODEL_DATA_2			1

#define MAX_REVIEW_SAMPLE		400		// One Tray

#define MAX_OFFLINE_LIST		2000

#define SELECTED_RESULT_NONE			0
#define SELECTED_RESULT_VISION_N1		1
#define SELECTED_RESULT_VISION_N2		2
#define SELECTED_RESULT_VISION_N3		3
#define SELECTED_RESULT_VISION_N4		4

#define LOG_COLOR_BLACK		0
#define LOG_COLOR_RED		1
#define LOG_COLOR_GREEN		2
#define LOG_COLOR_BLUE		3

#define IMAGE_SCALE_AUTO	0
#define IMAGE_SCALE_MANUAL	1

#define IMAGE_EDGE_ANY_DIR	0
#define IMAGE_EDGE_X_DIR	1
#define IMAGE_EDGE_Y_DIR	2

#define CONDITION_AND		0
#define CONDITION_OR		1

//////////////////////////////////////////////////////////////////////////
//	L10
//////////////////////////////////////////////////////////////////////////

#define MAX_INSPECTION_TYPE		23

#if defined (UAVI_AKC) || defined (UAVI_BOI) || defined (UAVI_ACT) || defined (UAVI_ATW) || defined (UAVI_BOS) || defined (UAVI_RENO) || defined (UAVI_KRIOS) || defined (SINGLE_LENS) || defined (ASSY_LENS)
#define INSPECTION_TYPE_MEASURE_FIRST	INSPECTION_TYPE_MEASURE_POINT
#define INSPECTION_TYPE_MEASURE_LAST	INSPECTION_TYPE_BLEND_POINT
// TODO : 여기는 왜 DATUM 이 없지?
// #define INSPECTION_TYPE_DATUM_START
// #define INSPECTION_TYPE_DATUM_END
#define INSPECTION_TYPE_MEASURE_START	INSPECTION_TYPE_MEASURE_POINT
#define INSPECTION_TYPE_MEASURE_END		INSPECTION_TYPE_BLEND_POINT
#endif

#if defined (UAVI_CHS_KS) || defined (UAVI_CHS_TV)
#define INSPECTION_TYPE_MEASURE_FIRST	INSPECTION_TYPE_CHS_MEASURE_DATUM_A_S1
#define INSPECTION_TYPE_MEASURE_LAST	INSPECTION_TYPE_CHS_MEASURE_FAI_19_P4
#define INSPECTION_TYPE_DATUM_START		INSPECTION_TYPE_CHS_MEASURE_DATUM_B_LINE1_P1
#define INSPECTION_TYPE_DATUM_END		INSPECTION_TYPE_CHS_MEASURE_DATUM_B_LINE4_P2
#define INSPECTION_TYPE_MEASURE_START	INSPECTION_TYPE_CHS_MEASURE_LENS_BARREL_TOP_P1
#define INSPECTION_TYPE_MEASURE_END		INSPECTION_TYPE_CHS_MEASURE_FAI_19_P4
#endif

#if defined (UAVI_CHS_WZ)
#define INSPECTION_TYPE_MEASURE_FIRST	INSPECTION_TYPE_CHS_MEASURE_DATUM_A_S1
#define INSPECTION_TYPE_MEASURE_LAST	INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_19_P4
#define INSPECTION_TYPE_DATUM_START		INSPECTION_TYPE_CHS_MEASURE_DATUM_B_LINE1_P1
#define INSPECTION_TYPE_DATUM_END		INSPECTION_TYPE_CHS_MEASURE_DATUM_B_LINE4_P2
#define INSPECTION_TYPE_MEASURE_START	INSPECTION_TYPE_CHS_WZ_MEASURE_LENS_BARREL_TOP_P1
#define INSPECTION_TYPE_MEASURE_END		INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_19_P4
#endif

// FAI INSPECTION TYPE
#define INSPECTION_TYPE_MEASURE_POINT 31
#define INSPECTION_TYPE_BLEND_POINT 32

#define INSPECTION_TYPE_FIRST	INSPECTION_TYPE_BARCODE
#define INSPECTION_TYPE_LAST	MAX_INSPECTION_TYPE

#define INSPECTION_TYPE_AUTO_UNDEFINED			-2
#define INSPECTION_TYPE_CROSS_BAR				-1

#define INSPECTION_TYPE_UNDEFINED				0		//
#define INSPECTION_TYPE_BARCODE					1		// BA

extern std::array<std::string, MAX_INSPECTION_TYPE> g_strInspectionTypeName;
extern std::array<std::string, MAX_INSPECTION_TYPE> g_strInspectionTypeName_Short;

#define INSPECTION_TYPE_DELETE					161		// 19 -> 161
#define INSPECTION_TYPE_ADD						162		// 20 -> 162
#define INSPECTION_TYPE_MASK					163		// 21 -> 163
#define INSPECTION_TYPE_UNUSED					164		// 22 -> 164
#define INSPECTION_TYPE_GLOBAL_ALIGN			165		// 23 -> 165
#define INSPECTION_TYPE_LOCAL_ALIGN				166		// 24 -> 166
#define INSPECTION_TYPE_LOCAL_ALIGN_ANGLE		167		// 25 -> 167
#define INSPECTION_TYPE_LIGHT					168		// 26 -> 168
#define INSPECTION_TYPE_FOCUS					169		// 27 -> 169
#define INSPECTION_TYPE_COLOR					170		// 28 -> 170
#define INSPECTION_TYPE_DONTCARE				171		// 29 -> 171
#define INSPECTION_TYPE_GENERATE				172		// 30 -> 172

#define INSPECTION_TYPE_AF_ALIGN				173		// 15 -> 173		
#define INSPECTION_TYPE_AF_ZIG_ROTATION_CENTER	174		// 16 -> 174
#define INSPECTION_TYPE_AF_NORTH_LINE			175		// 17 -> 175
#define INSPECTION_TYPE_AF_WEST_LINE			176		// 18 -> 176

// CM CHS COMMON
#define INSPECTION_TYPE_CHS_MEASURE_DATUM_A_S1						31
#define INSPECTION_TYPE_CHS_MEASURE_DATUM_A_S2						32
#define INSPECTION_TYPE_CHS_MEASURE_DATUM_A_S3						33
#define INSPECTION_TYPE_CHS_MEASURE_DATUM_A_S4						34
#define INSPECTION_TYPE_CHS_MEASURE_DATUM_B_LINE1_P1				35
#define INSPECTION_TYPE_CHS_MEASURE_DATUM_B_LINE1_P2				36
#define INSPECTION_TYPE_CHS_MEASURE_DATUM_B_LINE2_P1				37
#define INSPECTION_TYPE_CHS_MEASURE_DATUM_B_LINE2_P2				38
#define INSPECTION_TYPE_CHS_MEASURE_DATUM_B_LINE3_P1				39
#define INSPECTION_TYPE_CHS_MEASURE_DATUM_B_LINE3_P2				40
#define INSPECTION_TYPE_CHS_MEASURE_DATUM_B_LINE3_P2				40
#define INSPECTION_TYPE_CHS_MEASURE_DATUM_B_LINE4_P1				41
#define INSPECTION_TYPE_CHS_MEASURE_DATUM_B_LINE4_P2				42

// CM CHS-KS
#define INSPECTION_TYPE_CHS_MEASURE_VCM_SC_TOP_A					43
#define INSPECTION_TYPE_CHS_MEASURE_VCM_SC_TOP_B					44
#define INSPECTION_TYPE_CHS_MEASURE_VCM_SC_TOP_C					45
#define INSPECTION_TYPE_CHS_MEASURE_VCM_SC_TOP_D					46
#define INSPECTION_TYPE_CHS_MEASURE_VCM_SC_TOP_E					47
#define INSPECTION_TYPE_CHS_MEASURE_VCM_SC_TOP_F					48
#define INSPECTION_TYPE_CHS_MEASURE_VCM_SC_TOP_G					49
#define INSPECTION_TYPE_CHS_MEASURE_VCM_SC_TOP_H					50
#define INSPECTION_TYPE_CHS_MEASURE_LENS_BARREL_TOP_P1				51
#define INSPECTION_TYPE_CHS_MEASURE_LENS_BARREL_TOP_P2				52
#define INSPECTION_TYPE_CHS_MEASURE_LENS_BARREL_TOP_P3				53
#define INSPECTION_TYPE_CHS_MEASURE_LENS_BARREL_TOP_P4				54
#define INSPECTION_TYPE_CHS_MEASURE_LENS_BARREL_TOP_P5				55
#define INSPECTION_TYPE_CHS_MEASURE_LENS_BARREL_TOP_P6				56
#define INSPECTION_TYPE_CHS_MEASURE_LENS_BARREL_TOP_P7				57
#define INSPECTION_TYPE_CHS_MEASURE_LENS_BARREL_TOP_P8				58
#define INSPECTION_TYPE_CHS_MEASURE_LENS_INNER_P1					59
#define INSPECTION_TYPE_CHS_MEASURE_LENS_INNER_P2					60
#define INSPECTION_TYPE_CHS_MEASURE_LENS_INNER_P3					61
#define INSPECTION_TYPE_CHS_MEASURE_LENS_INNER_P4					62
#define INSPECTION_TYPE_CHS_MEASURE_LENS_INNER_P5					63
#define INSPECTION_TYPE_CHS_MEASURE_LENS_INNER_P6					64
#define INSPECTION_TYPE_CHS_MEASURE_LENS_INNER_P7					65
#define INSPECTION_TYPE_CHS_MEASURE_LENS_INNER_P8					66
#define INSPECTION_TYPE_CHS_MEASURE_FAI_7_WEST_A					67
#define INSPECTION_TYPE_CHS_MEASURE_FAI_7_WEST_B					68
#define INSPECTION_TYPE_CHS_MEASURE_FAI_7_EAST_P1					69
#define INSPECTION_TYPE_CHS_MEASURE_FAI_7_EAST_P2					70
#define INSPECTION_TYPE_CHS_MEASURE_FAI_9_WEST_P1					71
#define INSPECTION_TYPE_CHS_MEASURE_FAI_9_WEST_P2					72
#define INSPECTION_TYPE_CHS_MEASURE_FAI_9_WEST_P3					73
#define INSPECTION_TYPE_CHS_MEASURE_FAI_9_WEST_P4					74
#define INSPECTION_TYPE_CHS_MEASURE_FAI_9_WEST_P5					75
#define INSPECTION_TYPE_CHS_MEASURE_FAI_9_EAST_A					76
#define INSPECTION_TYPE_CHS_MEASURE_FAI_9_EAST_B					77
#define INSPECTION_TYPE_CHS_MEASURE_FAI_9_EAST_C					78
#define INSPECTION_TYPE_CHS_MEASURE_FAI_10_NORTH_A					79
#define INSPECTION_TYPE_CHS_MEASURE_FAI_10_NORTH_B					80
#define INSPECTION_TYPE_CHS_MEASURE_FAI_10_NORTH_C					81
#define INSPECTION_TYPE_CHS_MEASURE_FAI_10_SOUTH_P1					82
#define INSPECTION_TYPE_CHS_MEASURE_FAI_10_SOUTH_P2					83
#define INSPECTION_TYPE_CHS_MEASURE_FAI_10_SOUTH_P3					84
#define INSPECTION_TYPE_CHS_MEASURE_VCM_SC_STEP_P1					85
#define INSPECTION_TYPE_CHS_MEASURE_VCM_SC_STEP_P2					86
#define INSPECTION_TYPE_CHS_MEASURE_VCM_SC_STEP_P3					87
#define INSPECTION_TYPE_CHS_MEASURE_VCM_SC_STEP_P4					88
#define INSPECTION_TYPE_CHS_MEASURE_FAI_18_NECK_EPOXY_P1			89
#define INSPECTION_TYPE_CHS_MEASURE_FAI_18_NECK_EPOXY_P2			90
#define INSPECTION_TYPE_CHS_MEASURE_FAI_18_NECK_EPOXY_P3			91
#define INSPECTION_TYPE_CHS_MEASURE_FAI_21_FLEX_A					92
#define INSPECTION_TYPE_CHS_MEASURE_FAI_21_FLEX_B					93
#define INSPECTION_TYPE_CHS_MEASURE_FAI_23_FLEX_A					94
#define INSPECTION_TYPE_CHS_MEASURE_FAI_23_FLEX_B					95
#define INSPECTION_TYPE_CHS_MEASURE_FAI_24_P1						96
#define INSPECTION_TYPE_CHS_MEASURE_FAI_24_P2						97
#define INSPECTION_TYPE_CHS_MEASURE_FAI_25_A						98
#define INSPECTION_TYPE_CHS_MEASURE_FAI_25_B						99
#define INSPECTION_TYPE_CHS_MEASURE_FAI_25_P1						100
#define INSPECTION_TYPE_CHS_MEASURE_FAI_25_P2						101
#define INSPECTION_TYPE_CHS_MEASURE_DC_1_P1							102
#define INSPECTION_TYPE_CHS_MEASURE_DC_1_P2							103
#define INSPECTION_TYPE_CHS_MEASURE_DC_1_P3							104
#define INSPECTION_TYPE_CHS_MEASURE_DC_1_P4							105
#define INSPECTION_TYPE_CHS_MEASURE_DC_1_P5							106
#define INSPECTION_TYPE_CHS_MEASURE_DC_1_P6							107
#define INSPECTION_TYPE_CHS_MEASURE_DC_1_P7							108
#define INSPECTION_TYPE_CHS_MEASURE_DC_1_P8							109
#define INSPECTION_TYPE_CHS_MEASURE_DC_1_P9							110
#define INSPECTION_TYPE_CHS_MEASURE_DC_1_P10						111
#define INSPECTION_TYPE_CHS_MEASURE_DC_1_P11						112
#define INSPECTION_TYPE_CHS_MEASURE_DC_1_P12						113
#define INSPECTION_TYPE_CHS_MEASURE_DC_1_P13						114
#define INSPECTION_TYPE_CHS_MEASURE_FAI_16_1_A						115
#define INSPECTION_TYPE_CHS_MEASURE_FAI_16_1_B						116
#define INSPECTION_TYPE_CHS_MEASURE_FAI_16_1_P1						117
#define INSPECTION_TYPE_CHS_MEASURE_FAI_16_1_P2						118
#define INSPECTION_TYPE_CHS_MEASURE_FAI_16_1_P3						119
#define INSPECTION_TYPE_CHS_MEASURE_FAI_16_1_P4						120
#define INSPECTION_TYPE_CHS_MEASURE_FAI_16_2_A						121
#define INSPECTION_TYPE_CHS_MEASURE_FAI_16_2_B						122
#define INSPECTION_TYPE_CHS_MEASURE_FAI_16_2_P1						123
#define INSPECTION_TYPE_CHS_MEASURE_FAI_16_2_P2						124
#define INSPECTION_TYPE_CHS_MEASURE_FAI_16_2_P3						125
#define INSPECTION_TYPE_CHS_MEASURE_FAI_16_2_P4						126
#define INSPECTION_TYPE_CHS_MEASURE_FAI_16_3_A						127
#define INSPECTION_TYPE_CHS_MEASURE_FAI_16_3_B						128
#define INSPECTION_TYPE_CHS_MEASURE_FAI_16_3_P1						129
#define INSPECTION_TYPE_CHS_MEASURE_FAI_16_3_P2						130
#define INSPECTION_TYPE_CHS_MEASURE_FAI_16_3_P3						131
#define INSPECTION_TYPE_CHS_MEASURE_FAI_16_3_P4						132
#define INSPECTION_TYPE_CHS_MEASURE_FAI_19_A						133
#define INSPECTION_TYPE_CHS_MEASURE_FAI_19_B						134
#define INSPECTION_TYPE_CHS_MEASURE_FAI_19_P1						135
#define INSPECTION_TYPE_CHS_MEASURE_FAI_19_P2						136
#define INSPECTION_TYPE_CHS_MEASURE_FAI_19_P3						137
#define INSPECTION_TYPE_CHS_MEASURE_FAI_19_P4						138

// CM CHS-WZ
#define INSPECTION_TYPE_CHS_WZ_MEASURE_VCM_SC_TOP_A					43
#define INSPECTION_TYPE_CHS_WZ_MEASURE_VCM_SC_TOP_B					44
#define INSPECTION_TYPE_CHS_WZ_MEASURE_VCM_SC_TOP_C					45
#define INSPECTION_TYPE_CHS_WZ_MEASURE_VCM_SC_TOP_D					46
#define INSPECTION_TYPE_CHS_WZ_MEASURE_VCM_SC_TOP_E					47
#define INSPECTION_TYPE_CHS_WZ_MEASURE_VCM_SC_TOP_F					48
#define INSPECTION_TYPE_CHS_WZ_MEASURE_VCM_SC_TOP_G					49
#define INSPECTION_TYPE_CHS_WZ_MEASURE_VCM_SC_TOP_H					50
#define INSPECTION_TYPE_CHS_WZ_MEASURE_LENS_BARREL_TOP_P1			51
#define INSPECTION_TYPE_CHS_WZ_MEASURE_LENS_BARREL_TOP_P2			52
#define INSPECTION_TYPE_CHS_WZ_MEASURE_LENS_BARREL_TOP_P3			53
#define INSPECTION_TYPE_CHS_WZ_MEASURE_LENS_BARREL_TOP_P4			54
#define INSPECTION_TYPE_CHS_WZ_MEASURE_LENS_BARREL_TOP_P5			55
#define INSPECTION_TYPE_CHS_WZ_MEASURE_LENS_BARREL_TOP_P6			56
#define INSPECTION_TYPE_CHS_WZ_MEASURE_LENS_BARREL_TOP_P7			57
#define INSPECTION_TYPE_CHS_WZ_MEASURE_LENS_BARREL_TOP_P8			58
#define INSPECTION_TYPE_CHS_WZ_MEASURE_LENS_INNER_P1				59
#define INSPECTION_TYPE_CHS_WZ_MEASURE_LENS_INNER_P2				60
#define INSPECTION_TYPE_CHS_WZ_MEASURE_LENS_INNER_P3				61
#define INSPECTION_TYPE_CHS_WZ_MEASURE_LENS_INNER_P4				62
#define INSPECTION_TYPE_CHS_WZ_MEASURE_LENS_INNER_P5				63
#define INSPECTION_TYPE_CHS_WZ_MEASURE_LENS_INNER_P6				64
#define INSPECTION_TYPE_CHS_WZ_MEASURE_LENS_INNER_P7				65
#define INSPECTION_TYPE_CHS_WZ_MEASURE_LENS_INNER_P8				66
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_3_WEST_A					67
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_3_WEST_B					68
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_3_EAST_P1				69
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_3_EAST_P2				70
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_9_WEST_P1				71
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_9_WEST_P2				72
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_9_WEST_P3				73
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_9_EAST_A					74
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_9_EAST_B					75
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_9_EAST_C					76
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_10_NORTH_A				77
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_10_NORTH_B				78
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_10_NORTH_C				79
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_10_SOUTH_P1				80
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_10_SOUTH_P2				81
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_14_NORTH_P1				82
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_14_NORTH_P2				83
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_14_SOUTH_P3				84
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_14_SOUTH_P4				85
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_18_NECK_EPOXY_A			86
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_18_NECK_EPOXY_B			87
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_18_NECK_EPOXY_C			88
#define INSPECTION_TYPE_CHS_WZ_MEASURE_VCM_SC_STEP_P1				89
#define INSPECTION_TYPE_CHS_WZ_MEASURE_VCM_SC_STEP_P2				90
#define INSPECTION_TYPE_CHS_WZ_MEASURE_VCM_SC_STEP_P3				91
#define INSPECTION_TYPE_CHS_WZ_MEASURE_VCM_SC_STEP_P4				92
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_21_FLEX_P1				93
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_21_FLEX_P2				94
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_22_FLEX_P1				95
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_22_FLEX_P2				96
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_24_P1					97
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_24_P2					98
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_24_P3					99
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_24_P4					100
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_25_P1					101
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_25_P2					102
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_25_P3					103
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_25_P4					104
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_17_1_A					105
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_17_1_B					106
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_17_1_P1					107
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_17_1_P2					108
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_17_1_P3					109
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_17_1_P4					110
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_17_2_A					111
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_17_2_B					112
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_17_2_P1					113
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_17_2_P2					114
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_17_2_P3					115
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_17_2_P4					116
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_17_3_A					117
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_17_3_B					118
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_17_3_P1					119
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_17_3_P2					120
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_17_3_P3					121
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_17_3_P4					122
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_19_A						123
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_19_B						124
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_19_P1					125
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_19_P2					126
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_19_P3					127
#define INSPECTION_TYPE_CHS_WZ_MEASURE_FAI_19_P4					128

//////////////////////////////////////////////////////////////////////////
// Defect Name (Inspection Type에 따라 다름 ==> Inspection Type 모두 동일 [20170623])
#define MAX_REVIEW_INDEX	10
#define MAX_DEFECT_NAME		150
#define DEFECT_CODE_BARCODE_READ						61
#define DEFECT_CODE_BARCODE_SHIFT						62
#define DEFECT_CODE_BARCODE_ROTATION					63
#define DEFECT_CODE_FAI_NG								70
#define DEFECT_CODE_LENS_PARTICLE						68

//////////////////////////////////////////////////////////////////////////

#define EDGE_NEGATIVE	0
#define EDGE_POSITIVE	1

#define ONE_POINT_EDGE_EXTEND_PXL			20

#define SURFACE_NG_IF_VERIFY_RESULT_NG		0
#define SURFACE_NG_IF_VERIFY_RESULT_GOOD	1

#define IMAGE_PROCESS_ARITHMETIC_ADD		0
#define IMAGE_PROCESS_ARITHMETIC_SUB		1
#define IMAGE_PROCESS_ARITHMETIC_MAX		2
#define IMAGE_PROCESS_ARITHMETIC_MIN		3
#define IMAGE_PROCESS_ARITHMETIC_DIFF_ABS	4

#define LOCAL_ALIGN_MATCHING_ROI_TYPE_MATCHING	0
#define LOCAL_ALIGN_MATCHING_ROI_TYPE_LINE_FIT		1

#define LOCAL_ALIGN_MATCHING_ROI_POSITION	0
#define LOCAL_ALIGN_MATCHING_ROI_SHAPE		1

#define LOCAL_ALIGN_FIT_LINE_ROI_TOP		0
#define LOCAL_ALIGN_FIT_LINE_ROI_BOTTOM		1
#define LOCAL_ALIGN_FIT_LINE_ROI_LEFT		2
#define LOCAL_ALIGN_FIT_LINE_ROI_RIGHT		3

#define POST_LOCAL_ALIGN_ROTATION_CENTER_MODELCENTER		0
#define POST_LOCAL_ALIGN_ROTATION_CENTER_LEFTTOP     		1
#define POST_LOCAL_ALIGN_ROTATION_CENTER_RIGHTTOP    		2
#define POST_LOCAL_ALIGN_ROTATION_CENTER_LEFTBOTTOM  		3
#define POST_LOCAL_ALIGN_ROTATION_CENTER_RIGHTBOTTOM		4

//////////////////////////////////////////////////////////////////////////
/// Image Type
#define CHANNEL_TYPE_COLOR	0
#define CHANNEL_TYPE_R		1
#define CHANNEL_TYPE_G		2
#define CHANNEL_TYPE_B		3
#define CHANNEL_TYPE_H		4
#define CHANNEL_TYPE_S		5
#define CHANNEL_TYPE_I		6
#define CHANNEL_NUM			7

static const std::array<std::string, 7> g_channel_type = {
	"C",
	"R",
	"G",
	"B",
	"H",
	"S",
	"I"
};

//////////////////////////////////////////////////////////////////////////
/// Image Resolution Type
#define RES_TYPE_5			0		// 5um
#define RES_TYPE_10			1		// 10um
#define RES_TYPE_20			2		// 20um

//////////////////////////////////////////////////////////////////////////
/// Raw Image Saving Thread Type
#define RAW_IMAGE_SAVE_THREAD_PC		0
#define RAW_IMAGE_SAVE_THREAD_CAMERA	1
#define RAW_IMAGE_SAVE_THREAD_THREAD	2

// Wait time
#define MAX_RESULT_WAIT_ITERATION			5000
#define MAX_RESULT_WAIT_SLEEP_TIME			5

//////////////////////////////////////////////////////////////////////////
/// Matching Algorithm Type
#define ALIGN_MATCHING_SHAPE			0
#define ALIGN_MATCHING_TEMPLATE			1
#define ALIGN_MATCHING_PERSPECTIVE		2

// Teaching Mode Camera Light Type
#define TEACHING_CAMERA_LIGHT_PAGE		0
#define TEACHING_CAMERA_LIGHT_ADDR		1

// GPU Proc Mode
#define GPU_PROC_MODE_SPECULAR			0
#define GPU_PROC_MODE_DIFFUSED			1

// Diffused Vision
#define DIFFUSED_USED_CONV_IMAGE_NUMBER		1
#define DIFFUSED_RAW_IMAGE_NUMBER			4
#define DIFFUSED_VISION_MAX_CONVERSION		7
#define DIFFUSED_MAX_SHAPE_IMAGE_NUMBER		2

// Specular Vision
#define DFM_USED_CONV_IMAGE_NUMBER			2
#define DFM_MAX_SPECULAR_IMAGE_NUMBER		1
#define DFM_MAX_SHAPE_IMAGE_NUMBER			2
#define DFM_IMAGE_COMBINE_CURVATURE			0
#define DFM_IMAGE_COMBINE_PHASE				1
#define SPV_RAW_IMAGE_NUMBER				8
#define DFM_VISION_MAX_CONVERSION			5

// DFM Live Type
#define DFM_LIVE_CONVERT_IMAGE		0
#define DFM_LIVE_RAW_IMAGE			1

// DFM Light Page
#define DFM_NORMAL_GRAB_MAX_PAGE		4

// DFM Grab Return Value
#define DFM_RET_NO_ERROR				1
#define DFM_RET_GRABDONE_ERROR			0
#define DFM_RET_PORT_ERROR				-1

// DFM Teaching Mode Grab Done Wait Time
#define DFM_TEACHING_MODE_GRAB_DONE_WAIT_TIME	10000

//////////////////////////////////////////////////////////////////////////
// Local Align
#define LINE_FIT_XDIR_OBJECT_TOP		0
#define LINE_FIT_XDIR_OBJECT_BOTTOM		1
#define LINE_FIT_YDIR_OBJECT_LEFT		2
#define LINE_FIT_YDIR_OBJECT_RIGHT		3
#define INVALID_ALIGN_RESULT	999999
#define NOT_ANGLE_LINE	-99999

//////////////////////////////////////////////////////////////////////////
// Image Filter
#define FILTER_TYPE_NOT_USED			0
#define FILTER_TYPE_MEAN				1
#define FILTER_TYPE_MEDIAN				2
#define FILTER_TYPE_GAUSS				3
#define FILTER_TYPE_SCALE_MAX			4
#define FILTER_TYPE_EMPHASIZE			5
#define FILTER_TYPE_GRAY_OPENING		6
#define FILTER_TYPE_GRAY_CLOSING		7
#define FILTER_TYPE_EXPONENT			8
#define FILTER_TYPE_LOG					9
#define FILTER_TYPE_ANISO_DIFFUSION		10
#define FILTER_TYPE_SHARPENING			11

#define OVERLAY_IMAGE_RESULT_FONT_SIZE	24
#define ROS_IMAGE_REVIEW_FONT_SIZE		25
#define ROS_DEFECT_CIRCLE_MIN_RADIUS	100
#define ROS_DEFECT_CIRCLE_MAX_RADIUS	300
#define ROS_FIXED_ZOOM_MAX_DEFECT_COUNT		3

#define INDEX_ZIG_NUMBER		12

#define NO_USED_SHAPE_RAWIMAGE	4

#define RESULT_VIEW_MEASURE_FONT_SIZE	26

//////////////////////////////////////////////////////////////////////////
// Interpolation Type
#define INTERPOLATION_NEAREST		0
#define INTERPOLATION_BILINEAR		1
#define INTERPOLATION_BICUBIC		2

//////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////
// HANDLER Button Status
#define H_STATUS_START	1
#define H_STATUS_STOP	0

//////////////////////////////////////////////////////////////////////////
// TIME-OUT
#define TIMEOUT_SEQ_MOVE 5000

//////////////////////////////////////////////////////////////////////////
// Blob Analysis Result Point Max
#define MAX_RESULT_DATA_POINT		5000

//////////////////////////////////////////////////////////////////////////
// Barcode Print Quality
#define PQ_STRICT_MODEL_YES				0
#define PQ_STRICT_MODEL_NO				1
#define PQ_POLARITY_DARK_ON_LIGHT		0
#define PQ_POLARITY_LIGHT_ON_DARK		1
#define PQ_POLARITY_ANY					2
#define PQ_MIRRORED_YES					0
#define PQ_MIRRORED_NO					1
#define PQ_MIRRORED_ANY					2
#define PQ_CONTRAST_TOLERANCE_LOW		0
#define PQ_CONTRAST_TOLERANCE_HIGH		1
#define PQ_CONTRAST_TOLERANCE_ANY		2
#define PQ_STRICT_QUIET_ZONE_YES		0
#define PQ_STRICT_QUIET_ZONE_NO			1
#define PQ_SYMBOL_SHAPE_RECTANGLE		0
#define PQ_SYMBOL_SHAPE_SQUARE			1
#define PQ_SYMBOL_SHAPE_ANY				2
#define PQ_SMALL_MODULES_ROBUSTNESS_LOW		0
#define PQ_SMALL_MODULES_ROBUSTNESS_HIGH	1
#define PQ_MODULE_GRID_FIXED			0
#define PQ_MODULE_GRID_VARIABLE			1
#define PQ_MODULE_GRID_ANY				2
#define PQ_MODULE_GAP_NO				0
#define PQ_MODULE_GAP_SMALL				1
#define PQ_MODULE_GAP_BIG				2
#define PQ_FINDER_PATTERN_TOLERANCE_LOW		0
#define PQ_FINDER_PATTERN_TOLERANCE_HIGH	1
#define PQ_FINDER_PATTERN_TOLERANCE_ANY		2

#define MAX_PRINT_QUALITY_GRADE		13

#define MAX_CONFORMAL_COATING_HEIGHT_POINT		1000

#define MATCHING_ANGLE_REF_LINE_X	0
#define MATCHING_ANGLE_REF_LINE_Y	1

//////////////////////////////////////////////////////////////////////////
//TCP Communication [ADJ]
#define UM_ADJ_SEND_IMAGE		WM_USER+9999
#define MAX_ADJ_SEND_TRY_CNT 3
#define ADJ_SERVER_PORT 9000
#define MAX_ADJ_CONNECT_NUM 2
#define RCV_DATA_SIZE 25
#define ADJ_SEND_TIMEOUT 10000
#define ADJ_EACH_IMAGE_SEND_TIMEOUT 50
#define PC1_MODULE_TIMEOUT 500
#define PC2_MODULE_TIMEOUT 500
#define PC3_MODULE_TIMEOUT 500
#define WAIT_RESULT_FROM_ADJ 300
#define RCV_TIMEOUT -1
#define RCV_WAIT -2
#define RCV_ERROR -3
#define WAIT_FAILED_ERROR -4
#define WAIT_ABANDONED_ERROR -5
#define UNEXCEPTED_ERROR -6
#define IMAGE_LOAD_ERROR -7
#define DEEP_MODEL_VIEW 16
#define DEEP_MODEL_NUM 32
#define MAX_DEFECT_CNT 100
#define PATH_LIST_NUM 32
//TCP Communication end
//////////////////////////////////////////////////////////////////////////

//DeepLearningKIT
#define SUA_IMG_SIZE 256
#define MAX_BUF_SIZE  SUA_IMG_SIZE * SUA_IMG_SIZE * 3
#define MAX_RCV_BUF_SIZE   SUA_IMG_SIZE*SUA_IMG_SIZE + SUA_IMG_SIZE
#define MAX_MODEL_NUM DEEP_MODEL_NUM*MAX_ADJ_CONNECT_NUM	//연산시 괄호 필수
//#define MAX_MODULE_NUM 60
#define MAX_MODULE_NUM MAX_MODULE_TRAY
#define MAX_IMAGE_COUNT 6
//DeepLearningKIT end
//////////////////////////////////////////////////////////////////////////

#define LENGTH_MAX	0
#define LENGTH_MIN	1

#define LENGTH_MIN_TOP		0
#define LENGTH_MIN_BOTTOM	1
#define LENGTH_MIN_LEFT		2
#define LENGTH_MIN_RIGHT	3

#define CONNECTOR_PIN_TOP		0
#define CONNECTOR_PIN_BOTTOM	1
#define CONNECTOR_PIN_LEFT		2
#define CONNECTOR_PIN_RIGHT		3

#define HOLE_FILL_ALL	0
#define HOLE_FILL_AREA	1

#define ROI_CONNECTION_OUTER	0
#define ROI_CONNECTION_INNER	1

#define MIN_BARCODE_CHAR_LENGTH	5		// 기존 10

#define RESULT_IMAGE_DEFECT_DISPLAY_SIZE	0
#define RESULT_IMAGE_DEFECT_DISPLAY_AREA	1

#define DISTANCE_MEASURE_POINT_NUMBER	4
#define CORNER_MEASURE_POINT_NUMBER	3

//////////////////////////////// Gap Measure
#define GAP_MEASURE_POINT_NUMBER	20

#define GAP_TYPE_GENERAL_1			0
#define GAP_TYPE_GENERAL_2			1
#define GAP_TYPE_GENERAL_3			2
#define GAP_TYPE_BUMPER_BASE_1		3
#define GAP_TYPE_BUMPER_BASE_2		4
#define GAP_TYPE_BUMPER_BASE_3		5
#define GAP_TYPE_BUMPER_BASE_4		6
#define GAP_TYPE_BUMPER_BASE_5		7
#define GAP_TYPE_BUMPER_BASE_6		8
#define GAP_TYPE_BASE_FLEX_1		9
#define GAP_TYPE_BASE_FLEX_2		10
#define GAP_TYPE_BASE_FLEX_3_1		11
#define GAP_TYPE_BASE_FLEX_3_2		12
#define GAP_TYPE_BASE_FLEX_PISMO	13
#define GAP_TYPE_BASE_FLEX_4		14
#define GAP_TYPE_RES7				15
#define GAP_TYPE_RES8				16
#define GAP_TYPE_RES9				17
#define GAP_TYPE_RES10				18
#define GAP_TYPE_RES11				19

//////////////////////////////// Gap Measure

#define DL_TYPE1_RULE				0
#define DL_TYPE2_RULE_CLA_DNN		1
#define DL_TYPE3_CLA_DNN			2
#define DL_TYPE4_SEG_DNN_RULE		3

#define TOP_MODULE_POS_CHECK_NOT_READY		-1
#define TOP_MODULE_POS_CHECK_RESULT_NG		0
#define TOP_MODULE_POS_CHECK_RESULT_GOOD	1

#define HANDLER_ERROR_CONT_DEFECT				7100
#define HANDLER_ERROR_ADJ_CONNECT				7114
#define HANDLER_ERROR_MODEL_AUTO_LOAD_FAIL		7117
#define HANDLER_ERROR_LASAGGREGATOR_CONNECT		7124
#define HANDLER_ERROR_GRAB_FAIL					7125
#define HANDLER_ERROR_LIGHT_CONTROLLER_CONNECT_FAIL	7126

// Model Auto Load Result Type
#define MODEL_AUTO_LOAD_RESULT_FAIL	0
#define MODEL_AUTO_LOAD_RESULT_SKIP	1
#define MODEL_AUTO_LOAD_RESULT_COMPLETE	2

#define DUAL_BLOB_BRIGHT_DEFECT			0
#define DUAL_BLOB_DARK_DEFECT			1

#define MULTI_MODULE_ALIGN_TARGET_MODULE	0
#define MULTI_MODULE_ALIGN_TARGET_MIRROR	1

#define MULTI_MODULE_VISION_TOP1	0
#define MULTI_MODULE_VISION_ALIGN	1

#define MULTI_MODULE_PART_CHECK_MODULE		0
#define MULTI_MODULE_PART_CHECK_EMPTY		1

#define NECK_EPOXY_INSPECT_EDGE		0
#define NECK_EPOXY_INSPECT_BLOB		1

#define NECK_EPOXY_CRACK_DIR_LEFT		0
#define NECK_EPOXY_CRACK_DIR_RIGHT		1
#define NECK_EPOXY_CRACK_DIR_CENTER		2

// Model Type - string-based identification (no recompile needed to add models)
// Model names are loaded from ModelNameCode.ini at startup.
#define MODEL_TYPE_MAX				20
#define EQUIP_MODEL_TYPE_UNDEFINE	(-1)

// LOG 저장 Type
#define SAVE_LOG_TYPE_DAY_SUMMARY					0
#define SAVE_LOG_TYPE_LOT_RESULT					1
#define SAVE_LOG_TYPE_DAY_LOT_RESULT				2
#define SAVE_LOG_TYPE_ADJ_DAY_SUMMARY				3
#define SAVE_LOG_TYPE_ADJ_LOT_RESULT				4
#define SAVE_LOG_TYPE_ADJ_DAY_LOT_RESULT			5
#define SAVE_LOG_TYPE_ADJ_TOTAL_IMAGE_SUMMARY		6
#define SAVE_LOG_TYPE_ADJ_DAY_SUMMARY_SKIP_RATE		7
#define SAVE_LOG_TYPE_ONLY_ADJ_LOT_RESULT			8
#define SAVE_LOG_TYPE_ONLY_ADJ_DAY_LOT_RESULT		9
#define SAVE_LOG_TYPE_MONITORING_GV_EDGE			10
#define SAVE_LOG_TYPE_MONITORING_CONT_DEFECT		11
#define SAVE_LOG_TYPE_DEFECT_SHAPE_FEATURE			12
#define SAVE_LOG_TYPE_LOT_RESULT_LASPC				13
#define SAVE_LOG_TYPE_DEFECT_VARIATION_FEATURE		14
#define SAVE_LOG_TYPE_INSPECT_CONDITION				15
#define SAVE_LOG_TYPE_ALL_DEFECTS_RESULT			16
#define SAVE_LOG_TYPE_CONTACT_POINT					17

#define ORTHO_LENGTH_TOP		0
#define ORTHO_LENGTH_BOTTOM		1
#define ORTHO_LENGTH_LEFT		2
#define ORTHO_LENGTH_RIGHT		3

#define VM_TRAIN_NOUSE			0
#define VM_TRAIN_ALL			1
#define VM_TRAIN_AUTO_OPTION	2

#define DFM_BAUD_RATE  115200

#define Z_MOVE_OFFSET	0.001
#define MOTION_NOUSE	-999

#define MODULE_INSPECT_STATUS_IDLE		0
#define MODULE_INSPECT_STATUS_LOAD		1
#define MODULE_INSPECT_STATUS_INSPECT	2

#define SHIP_TRAY_TYPE_NG_STAGE1	1
#define SHIP_TRAY_TYPE_NG_STAGE2	2
#define SHIP_TRAY_TYPE_GOOD_STAGE1	3
#define SHIP_TRAY_TYPE_GOOD_STAGE2	4

#define GAP_MEASURE_SELECT_MAX		0
#define GAP_MEASURE_SELECT_MIN		1

#define TOP1_MODULE_ROTATION_MEASURE_IMAGE_INDEX	13

////////////////////////////////

//Ver 1026 add start
#define IMAGE_SAVE_THREAD_MAX_QUEUE		10
#define RAW_IMAGE_TEMP_DRIVE_NUMBER     3
#define IMAGE_AXIS_SPLIT_VALUE		5
//Ver 1026 add end

#define MAX_COMBINE_IMAGE_NUMBER	6

// FAI
#define MAX_FAI_PARAMETER			1		// 3 -> 1
#define MAX_ONE_FAI_MEASURE_VALUE	13
#define MAX_TILT_MEASURE_POINT		2

#define FAI_RESULT_CASE_GOOD			0
#define FAI_RESULT_CASE_NG				1
#define FAI_RESULT_CASE_MIXED			2

#define HEIGHT_INIT					-999999

// Matching
#define MAX_PYRAMID_LEVEL_TEMPALTE		6
#define MAX_PYRAMID_LEVEL_SHAPE			6

#define BUFFER_STATUS_INSPECTING		0
#define BUFFER_STATUS_POSTPROCESSING	1
#define BUFFER_STATUS_AVAILABLE			2

#endif

#define WM_AISETUP_EXITED    (WM_USER + 100)

#define WM_AF_ZIG_ROT_CENTER_RESULT   (WM_APP + 101)
#define LOG_CSTR(cstr) CT2A(cstr).m_psz

//Single Lens AutoRun Grab Type
#define USE_INTERRUPT
