#define MAX_CLIENT_NUM 2
#define MAX_MULTI_CONNECTION_NUM 10
#define NET_EVNET_NUM 1
#define NET_EVENT_WAIT_TIME 800
#define SOCKET_CLOSE -2
#define MAX_BUF_SIZE (1024*1024*3*3)
#define PACKET_FILE_NAME_SIZE 200
#define PACKET_STRING_SIZE 100
#define PACKET_IMAGE_SIZE (256*256*3)
#define PACKET_IMAGE_COUNT 6

#define CONNECT_EVENT 0
#define RECV_EVENT 1
#define SERVER_CLOSE_EVENT 2
#define RESTART_EVENT 3 //jwj 190819 add
#define TCP_EVENT_NUM 4